[tool.poetry]
name = "Funkwhale"
version = "1.2.1"
description = ""
authors = ["Funkwhale Collective"]
license = "GNU AGPLv3"

[tool.poetry.dependencies]
python = "^3.7"
Django = "~=3.2.3"
setuptools = "~=57.4.0"
django-environ = "~=0.4.0"
Pillow = "~=8.3.0"
django-allauth = "~=0.42.0"
psycopg2 = "~=2.9.1"
pytz = "2021.1"
django-redis = "~=5.0.0"
redis = "~=3.5.0"
kombu = "~=5.1.0"
celery = "~=5.1.2"
django-cors-headers = "~=3.8.0"
musicbrainzngs = "~=0.7.1"
djangorestframework = "~=3.12.2"
arrow = "~=1.1.0"
persisting-theory = "~=0.2.0"
django-versatileimagefield = "~=2.2.0"
django-filter = "~=2.4.0"
django-rest-auth = "~=0.9.0"
mutagen = "~=1.45.0"
PyMemoize = "~=1.0.0"
django-dynamic-preferences = "~=1.10"
python-magic = "~=0.4.0"
channels = "~=3.0.3"
channels-redis = "~=3.3.0"
gunicorn = "~=20.1.0"
cryptography = ">=3.3.2"
requests-http-signature = {git = "https://github.com/agateblue/requests-http-signature.git", rev = "signature-header-support"}
django-cleanup = "~=5.2.0"
requests = "~=2.26.0"
pyOpenSSL = "~=20.0.1"
pydub = "~=0.25.1"
PyLD = "~=2.0.3"
aiohttp = "~=3.7.4"
django-oauth-toolkit = "~=1.5.0"
django-storages = "~=1.11.1"
boto3 = "~=1.17.59"
unicode-slugify = "~=0.1.0"
django-cacheops = "~=6.0.0"
service-identity = "~=21.1.0"
click = "~=7.1.0"
Markdown = "~=3.3.4"
bleach = "~=3.3.0"
feedparser = "~=6.0.0"
watchdog = "~=2.1.2"
asgiref = "3.3.4" #1516
ipython = "~=7.27.0"
python-ldap = "~=3.3.0"
django-auth-ldap = "~=3.0.0"
uvicorn = {version = "~=0.14.0", extras = ["standard"]}

[tool.poetry.dev-dependencies]
flake8 = "~=3.9.1"
pytest = "~=6.2.3"
pytest-cov = "~=2.12.0"
pytest-django = "~=4.4.0"
pytest-env = "~=0.6.0"
pytest-mock = "~=3.6.0"
pytest-randomly = "~=3.10.1"
pytest-sugar = "~=0.9.0"
pytest-asyncio = "~=0.15.1"
requests-mock = "~=1.9.0"
Faker = "~=8.12.1"
coverage = "~=5.5.0"
django-coverage-plugin = "~=2.0.0"
factory-boy = "~=3.2.0"
django-debug-toolbar = "~=3.2.1"
asynctest = "~=0.13.0"
aioresponses = "~=0.7.2"
prompt-toolkit = "~=3.0.18"
black = "~=21.4b1"
ipdb = "~=0.13.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
