[tool.poetry]
name = "Funkwhale"
version = "1.2.1"
description = ""
authors = ["Funkwhale Collective"]
license = "GNU AGPLv3"

[tool.poetry.dependencies]
python = "^3.7"
Django = "==3.2.12"
setuptools = "==57.5.0"
django-environ = "==0.8.1"
Pillow = "==9.0.1"
django-allauth = "==0.42.0"
psycopg2 = "==2.9.3"
pytz = "2021.3"
django-redis = "==5.2.0"
redis = "==4.1.2"
kombu = "==5.2.3"
celery = "==5.2.3"
django-cors-headers = "==3.11.0"
musicbrainzngs = "==0.7.1"
djangorestframework = "==3.13.1"
arrow = "==1.2.2"
persisting-theory = "==0.2.1"
django-versatileimagefield = "==2.2"
django-filter = "==21.1"
django-rest-auth = "==0.9.5"
mutagen = "==1.45.1"
django-dynamic-preferences = "==1.11.0"
python-magic = "==0.4.25"
channels = "==3.0.4"
channels-redis = "==3.3.1"
gunicorn = "==20.1.0"
cryptography = "==36.0.1"
requests-http-signature = {git = "https://github.com/agateblue/requests-http-signature.git", rev = "signature-header-support"}
django-cleanup = "==6.0.0"
requests = "==2.27.1"
pyOpenSSL = "21.0.0"
pydub = "==0.25.1"
PyLD = "==2.0.3"
aiohttp = "==3.8.1"
django-oauth-toolkit = "==1.7.0"
django-storages = "==1.12.3"
boto3 = "==1.20.49"
unicode-slugify = "==0.1.5"
django-cacheops = "==6.0"
service-identity = "==21.1.0"
click = "==8.0.3"
Markdown = "==3.3.6"
bleach = "==4.1.0"
feedparser = "==6.0.8"
watchdog = "==2.1.6"
asgiref = "==3.5.0" #1516
ipython = "==7.31.1"
python-ldap = "==3.4.0"
django-auth-ldap = "==4.0.0"
uvicorn = {version = "==0.17.4", extras = ["standard"]}
django-cache-memoize = "^0.1.10"

[tool.poetry.dev-dependencies]
flake8 = "==3.9.2"
pytest = "==6.2.5"
pytest-cov = "==3.0.0"
pytest-django = "==4.5.2"
pytest-env = "==0.6.2"
pytest-mock = "==3.7.0"
pytest-randomly = "==3.11.0"
pytest-sugar = "==0.9.4"
pytest-asyncio = "==0.17.2"
requests-mock = "==1.9.3"
Faker = "==12.0.1"
coverage = "==6.3.1"
django-coverage-plugin = "==2.0.2"
factory-boy = "==3.2.1"
django-debug-toolbar = "==3.2.4"
asynctest = "==0.13.0"
aioresponses = "==0.7.3"
prompt-toolkit = "==3.0.26"
black = "==22.1.0"
ipdb = "==0.13.9"
drf-spectacular = "==0.21.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
